{% set name = "neurodocker" %}
{% set version = "2.0.0" %}
{% set sha256 = "de3b9c2f8004f1e7a522586e68e78e2f9b5cf07092e684ebffad00b430f05043" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neurodocker-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - neurodocker = neurodocker.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - click >=7.0,<8.0
    - etelemetry >=0.2.0
    - jinja2 >=2.0
    - jsonschema >=3.0
    - mypy_extensions
    - python >=3.7
    - pyyaml >=5.0
    - typing-extensions

test:
  imports:
    - neurodocker
  commands:
    - neurodocker --help

about:
  home: https://github.com/ReproNim/neurodocker
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neurodocker is a command-line program that generates custom Dockerfiles and Singularity recipes for neuroimaging and minifies existing containers.

extra:
  recipe-maintainers:
    - npavlovikj
    - acaprez
