{% set name = "neurodocker" %}
{% set version = "2.0.1" %}
{% set sha256 = "ce5c572f013daa3a45341e3e5d8164d345c7df99a8aa14f5f3c821150ffceeb8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neurodocker-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - neurodocker = neurodocker.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - click >=7.0,<8.0
    - etelemetry >=0.2.0
    - jinja2 >=2.0
    - jsonschema >=3.0
    - mypy_extensions
    - python >=3.7
    - pyyaml >=5.0
    - typing-extensions

test:
  imports:
    - neurodocker
  commands:
    - neurodocker --help

about:
  home: https://github.com/ReproNim/neurodocker
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neurodocker is a command-line program that generates custom Dockerfiles and Singularity recipes for neuroimaging and minifies existing containers.

extra:
  recipe-maintainers:
    - npavlovikj
    - acaprez
